name: pexo
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.1.1
  - python=3.7.1
  - astropy=4.0.1
  - numpy=1.18.1
  - matplotlib=3.2.2
  - ipykernel=5.3.0
  - r-base=3.6.1
  - r-cowplot=1.0.0
  - r-cubature=2.0.4
  - r-domc=1.3.6
  - r-doparallel
  - r-e1071=1.7_3
  - r-fields=10.3
  - r-foreach=1.5.0
  - r-ggplot2=3.3.2
  - r-glasso=1.11
  - r-gridextra=2.3
  - r-hyperbolicdist=0.6_2
  - r-jpen=1.0
  - r-kernlab=0.9_29
  - r-ks=1.11.7
  - r-lattice=0.20_41
  - r-matrix=1.2_18
  - r-matrixcalc=1.0_3
  - r-mvtnorm=1.1_1
  - r-numderiv=2016.8_1.1
  - r-optparse=1.6.6
  - r-orthopolynom=1.0_5
  - r-pracma=2.2.9
  - r-rootsolve=1.8.2.1
  - pip:
    - astroquery==0.4.1
    - argparse==1.4.0
